### ISSUE TITLE
Mega menu is glitchy when moving from the menu item to the mega menu panel

### ISSUE THREAD

**Issue by theadamparker** [undp/design-system#915] opened 2022-03-30 14:55 UTC
Hovering from the menu item (e.g. _who we are_, _what we do_) to the mega menu panel should be a seamless experience. However it is experiencing bugginess and begins to collapse while moving the cursor from one position to the next. See screen capture for a better explanation. 

Correct behavior is for the mega menu not to collape when moving from menu item to mega menu panel, or when moving from menu item to menu item. There should be significant padding around the hoverable area to create a smooth and forgiving hovering experience. 

https://user-images.githubusercontent.com/2205158/160864337-108f0c63-2d16-4060-8a25-593228070755.mov

Tested on MacOS 10.14.6 Chrome 99.0.4844.84

**Comment by paboden** [comment] 2023-02-01 06:58
I addressed the glitchy issue in another task #916 because the css work was so close together.

**Comment by paboden** [comment] 2023-02-01 21:54
@theadamparker did you get a chance to review this one while checking the #916 task? It may have been fixed by that other task.

**Comment by Jura** [comment] 2023-03-01 19:11
@paboden , there is a regression identified in Firefox: https://develop.design-system.pages.dev/?path=/story/templates-global-homepage--global-homepage , mega menu is not closing when you are moving mouse outside of the menu. Chrome works fine
It worked fine before: https://design.undp.org/?path=/story/templates-global-homepage--global-homepage

**Comment by Jura** [comment] 2023-03-02 15:19
@mrelevo , please verify

**Comment by mrelevo** [comment] 2023-03-02 16:47
verified in Dev

**Closed by mrelevo** 2023-03-02 16:47 UTC
Labels: bug, extdev

**Comment by mrelevo** [comment] 2023-05-09 20:24
verified in storybook and Drupal DEV
